/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package estruturaSe;
public class App {
    public static void main(String[] args) {
        
        int media = 6;
        
        if(media >= 7){
            
            System.out.print("Aprovado");
                         
        } else{
        System.out.print("Reprovado");
        }
        
         
    }
}
