/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package estruturaEscolha;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        int num;
        
        Scanner leitor = new Scanner(System.in);
        
        num = leitor.nextInt();
        
        if (num >= 100 && num <= 200){
            
            System.out.println("ESTA NO INTERVALO");
        
        }else{
            System.out.println("NAO ESTA NO INTERVALO");
        
        
        }
        
    }
}
